services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate:v1.8.3
    ports:
      - "5050:5000"
    restart: unless-stopped

    environment:
      - LT_UPDATE_MODELS=true

    volumes:
      - libretranslate_models:/home/libretranslate/.local:rw

volumes:
  libretranslate_models:
